name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt

    - name: Install Node.js dependencies
      run: npm install

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build .exe with PyInstaller
      run: |
        pyinstaller --onefile ^
          --paths=src/libs ^
          --add-data "src/utils;utils" ^
          --add-data "src/instagram_scripts/upload.js;instagram_scripts" ^
          --add-data "src/instagram_scripts/logs;instagram_scripts/logs" ^
          --add-data "node_modules;node_modules" ^
          --add-data "package.json;." ^
          --hidden-import=asyncio.base_events ^
          --exclude-module=logger ^
          --clean ^
          src/app.py

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: desktop-app-windows
        path: dist/*.exe
